# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d52e84dd6b97a831b0b2688a2acddd45a0e67ada5eca564f36f5ecb6c46f072a4785d5159e5ae9716b381db19a9d2d2f932994aea17b8a6eb5b224188b239dee

test:
  secret_key_base: 526d3bd85a54df80db0ff806e8637f9bf8cad8b8e487c35c74fcbd7dc3ff044649acd271a6d6f3fa98f64bec32b6cfb81c4753a8b4bfcc2a41213285f0bd1bda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
